In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # data visualization library  
import matplotlib.pyplot as plt

In [2]:
train_df = pd.read_csv('training.csv')
test_df = pd.read_csv('test.csv')

In [3]:
train_df.head()

EventId  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0   100000       138.470                       51.655        97.827    27.980   
1   100001       160.937                       68.768       103.235    48.146   
2   100002      -999.000                      162.172       125.953    35.635   
3   100003       143.905                       81.417        80.943     0.414   
4   100004       175.864                       16.915       134.805    16.405   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0                  0.91           124.711                2.666   
1               -999.00          -999.000             -999.000   
2               -999.00          -999.000             -999.000   
3               -999.00          -999.000             -999.000   
4               -999.00          -999.000             -999.000   

   DER_deltar_tau_lep  DER_pt_tot  ...  PRI_jet_num  PRI_jet_leading_pt  \
0               3.064      41.928  ...            2              67.435   
1               3.473       2.078  ...            1              46.226   
2               3.148       9.336  ...            1              44.251   
3               3.310       0.414  ...            0            -999.000   
4               3.891      16.405  ...            0            -999.000   

   PRI_jet_leading_eta  PRI_jet_leading_phi  PRI_jet_subleading_pt  \
0                2.150                0.444                 46.062   
1                0.725                1.158               -999.000   
2                2.053               -2.028               -999.000   
3             -999.000             -999.000               -999.000   
4             -999.000             -999.000               -999.000   

   PRI_jet_subleading_eta  PRI_jet_subleading_phi  PRI_jet_all_pt    Weight  \
0                    1.24                  -2.475         113.497  0.002653   
1                 -999.00                -999.000          46.226  2.233584   
2                 -999.00                -999.000          44.251  2.347389   
3                 -999.00                -999.000          -0.000  5.446378   
4                 -999.00                -999.000           0.000  6.245333   

   Label  
0      s  
1      b  
2      b  
3      b  
4      b  

[5 rows x 33 columns]

In [4]:
test_df.head()

EventId  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0   350000      -999.000                       79.589        23.916     3.036   
1   350001       106.398                       67.490        87.949    49.994   
2   350002       117.794                       56.226        96.358     4.137   
3   350003       135.861                       30.604        97.288     9.104   
4   350004        74.159                       82.772        58.731    89.646   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0              -999.000          -999.000             -999.000   
1              -999.000          -999.000             -999.000   
2              -999.000          -999.000             -999.000   
3              -999.000          -999.000             -999.000   
4                 1.347           536.663               -0.339   

   DER_deltar_tau_lep  DER_pt_tot  ...  PRI_met_phi  PRI_met_sumet  \
0               0.903       3.036  ...        2.022         98.556   
1               2.048       2.679  ...       -1.138        176.251   
2               2.755       4.137  ...       -1.868        111.505   
3               2.811       9.104  ...        1.172        164.707   
4               1.028      77.213  ...       -0.231        869.614   

   PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  PRI_jet_leading_phi  \
0            0            -999.000             -999.000             -999.000   
1            1              47.575               -0.553               -0.849   
2            0            -999.000             -999.000             -999.000   
3            0            -999.000             -999.000             -999.000   
4            3             254.085               -1.013               -0.334   

   PRI_jet_subleading_pt  PRI_jet_subleading_eta  PRI_jet_subleading_phi  \
0               -999.000                -999.000                -999.000   
1               -999.000                -999.000                -999.000   
2               -999.000                -999.000                -999.000   
3               -999.000                -999.000                -999.000   
4                185.857                   0.335                   2.587   

   PRI_jet_all_pt  
0          -0.000  
1          47.575  
2           0.000  
3           0.000  
4         599.213  

[5 rows x 31 columns]

In [5]:
list = ['EventId', 'Weight', 'Label']
X_train = train_df.drop(list, axis = 1)
X_train.head()

DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  DER_pt_h  \
0       138.470                       51.655        97.827    27.980   
1       160.937                       68.768       103.235    48.146   
2      -999.000                      162.172       125.953    35.635   
3       143.905                       81.417        80.943     0.414   
4       175.864                       16.915       134.805    16.405   

   DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0                  0.91           124.711                2.666   
1               -999.00          -999.000             -999.000   
2               -999.00          -999.000             -999.000   
3               -999.00          -999.000             -999.000   
4               -999.00          -999.000             -999.000   

   DER_deltar_tau_lep  DER_pt_tot  DER_sum_pt  ...  PRI_met_phi  \
0               3.064      41.928     197.760  ...       -0.277   
1               3.473       2.078     125.157  ...       -1.916   
2               3.148       9.336     197.814  ...       -2.186   
3               3.310       0.414      75.968  ...        0.060   
4               3.891      16.405      57.983  ...       -0.871   

   PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
0        258.733            2              67.435                2.150   
1        164.546            1              46.226                0.725   
2        260.414            1              44.251                2.053   
3         86.062            0            -999.000             -999.000   
4         53.131            0            -999.000             -999.000   

   PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
0                0.444                 46.062                    1.24   
1                1.158               -999.000                 -999.00   
2               -2.028               -999.000                 -999.00   
3             -999.000               -999.000                 -999.00   
4             -999.000               -999.000                 -999.00   

   PRI_jet_subleading_phi  PRI_jet_all_pt  
0                  -2.475         113.497  
1                -999.000          46.226  
2                -999.000          44.251  
3                -999.000          -0.000  
4                -999.000           0.000  

[5 rows x 30 columns]

In [6]:
Y_train = train_df[['Label']]
Y_train.head()

Label
0     s
1     b
2     b
3     b
4     b

In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

le.fit(Y_train['Label'])
Y_train['Label'] = le.transform(Y_train['Label'])

Y_train.head()

c:\users\yash\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


Label
0      1
1      0
2      0
3      0
4      0

In [8]:
from sklearn.impute  import SimpleImputer

imputer = SimpleImputer(missing_values = -999.0, strategy = 'most_frequent')
X_train = imputer.fit_transform(X_train)

In [9]:
X_train

array([[138.47 ,  51.655,  97.827, ...,   1.24 ,  -2.475, 113.497],
       [160.937,  68.768, 103.235, ...,  -1.699,  -2.135,  46.226],
       [ 96.415, 162.172, 125.953, ...,  -1.699,  -2.135,  44.251],
       ...,
       [105.457,  60.526,  75.839, ...,  -1.699,  -2.135,  41.992],
       [ 94.951,  19.362,  68.812, ...,  -1.699,  -2.135,   0.   ],
       [ 96.415,  72.756,  70.831, ...,  -1.699,  -2.135,   0.   ]])

In [10]:
from sklearn.ensemble import GradientBoostingClassifier as GBC

gbc = GBC(n_estimators=50, max_depth=5,min_samples_leaf=200,max_features=10,verbose=1)
gbc.fit(X_train,Y_train) 

c:\users\yash\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\_gb.py:1454: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


      Iter       Train Loss   Remaining Time 
         1           1.2185            1.50m
         2           1.1591            1.48m
         3           1.1113            1.42m
         4           1.0697            1.39m
         5           1.0377            1.36m
         6           1.0070            1.33m
         7           0.9803            1.29m
         8           0.9570            1.26m
         9           0.9353            1.23m
        10           0.9169            1.20m
        20           0.8163           54.05s
        30           0.7785           36.14s
        40           0.7581           18.29s
        50           0.7451            0.00s


GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=5,
                           max_features=10, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=200, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=50,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=1,
                           warm_start=False)

In [19]:
train_predict = gbc.predict_proba(X_train)[:,1]

list = ['EventId']
X_test = test_df.drop(list, axis = 1)

Y_predict = gbc.predict_proba(X_test)[:,1]
Y_predict

array([0.0506323 , 0.16933   , 0.6404774 , ..., 0.0974943 , 0.54793714,
       0.29419175])

In [22]:
pcut = np.percentile(train_predict,85)
label_test = Y_predict > pcut

label_test

array([False, False, False, ..., False, False, False])

In [29]:
result = []
for x in range(len(test_df['EventId'])):
    result.append([int(test_df['EventId'][x]), Y_predict[x], 's'*(label_test[x]==True)+'b'*(label_test[x]==False)])

result

c:\users\yash\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  This is separate from the ipykernel package so we can avoid doing imports until


[[350000, 0.050632297279883096, 'b'],
 [350001, 0.1693299960828791, 'b'],
 [350002, 0.6404774003127823, 'b'],
 [350003, 0.8521062763657284, 's'],
 [350004, 0.05149812305221762, 'b'],
 [350005, 0.19842904328350575, 'b'],
 [350006, 0.1925540202997849, 'b'],
 [350007, 0.03139835651173532, 'b'],
 [350008, 0.10400445050741912, 'b'],
 [350009, 0.8129808037302096, 's'],
 [350010, 0.0814938246922972, 'b'],
 [350011, 0.2413452908160791, 'b'],
 [350012, 0.5952224357595816, 'b'],
 [350013, 0.08498628851364451, 'b'],
 [350014, 0.05725380491596035, 'b'],
 [350015, 0.04583042397750776, 'b'],
 [350016, 0.20133201852706406, 'b'],
 [350017, 0.09379287344189635, 'b'],
 [350018, 0.07356007012983667, 'b'],
 [350019, 0.7714140307350987, 'b'],
 [350020, 0.14463081326766627, 'b'],
 [350021, 0.06652708245807289, 'b'],
 [350022, 0.0819718844680983, 'b'],
 [350023, 0.09709960647425088, 'b'],
 [350024, 0.12316567939965936, 'b'],
 [350025, 0.4491828384287281, 'b'],
 [350026, 0.6764847303824302, 'b'],
 [350027, 0.

In [34]:
result = sorted(result, key = lambda x: x[1])

for i in range(len(result)):
    result[i][1] = i+1

result

[[359958, 1, 'b'],
 [746208, 2, 'b'],
 [596371, 3, 'b'],
 [469430, 4, 'b'],
 [772769, 5, 'b'],
 [421192, 6, 'b'],
 [750054, 7, 'b'],
 [503404, 8, 'b'],
 [446821, 9, 'b'],
 [499094, 10, 'b'],
 [415492, 11, 'b'],
 [616283, 12, 'b'],
 [634167, 13, 'b'],
 [511999, 14, 'b'],
 [687980, 15, 'b'],
 [670135, 16, 'b'],
 [524232, 17, 'b'],
 [453392, 18, 'b'],
 [560144, 19, 'b'],
 [737843, 20, 'b'],
 [818139, 21, 'b'],
 [658726, 22, 'b'],
 [813646, 23, 'b'],
 [787957, 24, 'b'],
 [895196, 25, 'b'],
 [848021, 26, 'b'],
 [813628, 27, 'b'],
 [576709, 28, 'b'],
 [604285, 29, 'b'],
 [481297, 30, 'b'],
 [867356, 31, 'b'],
 [507215, 32, 'b'],
 [372690, 33, 'b'],
 [460317, 34, 'b'],
 [645096, 35, 'b'],
 [577051, 36, 'b'],
 [792064, 37, 'b'],
 [472596, 38, 'b'],
 [382941, 39, 'b'],
 [720813, 40, 'b'],
 [695782, 41, 'b'],
 [618333, 42, 'b'],
 [561931, 43, 'b'],
 [593619, 44, 'b'],
 [580003, 45, 'b'],
 [894629, 46, 'b'],
 [729617, 47, 'b'],
 [357315, 48, 'b'],
 [835421, 49, 'b'],
 [646717, 50, 'b'],
 [742746,

In [37]:
#sort according to the index
result = sorted(result, key = lambda x: x[0])

In [38]:
file = open('submission.csv','w')
file.write('EventId,RankOrder,Class\n')

for entry in result:
    ent = str(entry[0]) + ',' + str(entry[1]) + ',' + str(entry[2]) + '\n'
    file.write(ent)
file.close()